"""Minimal ICC v4.4 profile builder for BT.2020 + PQ, with a `cicp` tag.

The `cicp` tag is the authoritative signal for HDR-aware colour engines. The
matrix/TRC tags exist so that engines which do not understand `cicp` still get
a sane approximation instead of nonsense.
"""
from __future__ import annotations

import struct
import numpy as np

BT2020_PRIMARIES = {"r": (0.708, 0.292), "g": (0.170, 0.797), "b": (0.131, 0.046)}
D65 = (0.3127, 0.3290)
D50_XYZ = np.array([0.9642, 1.0000, 0.8249])

BRADFORD = np.array([[0.8951, 0.2664, -0.1614],
                     [-0.7502, 1.7135, 0.0367],
                     [0.0389, -0.0685, 1.0296]])


def _xy_to_XYZ(x, y):
    return np.array([x / y, 1.0, (1.0 - x - y) / y])


def _rgb_to_xyz_d50():
    cols = np.array([_xy_to_XYZ(*BT2020_PRIMARIES[k]) for k in "rgb"]).T
    w = _xy_to_XYZ(*D65)
    scale = np.linalg.solve(cols, w)
    m = cols * scale                       # RGB -> XYZ under D65
    src, dst = BRADFORD @ w, BRADFORD @ D50_XYZ
    adapt = np.linalg.inv(BRADFORD) @ np.diag(dst / src) @ BRADFORD
    return adapt @ m                       # RGB -> XYZ under D50


def _s15f16(v: float) -> int:
    return int(round(v * 65536.0)) & 0xFFFFFFFF


def _xyz_tag(col) -> bytes:
    return b"XYZ " + b"\0" * 4 + struct.pack(
        ">III", _s15f16(col[0]), _s15f16(col[1]), _s15f16(col[2]))


def _pq_curve(n: int = 1024) -> bytes:
    """Sampled PQ EOTF, normalised so signal 1.0 -> PCS 1.0 (10000 cd/m^2)."""
    v = np.linspace(0.0, 1.0, n)
    m1, m2 = 0.1593017578125, 78.84375
    c1, c2, c3 = 0.8359375, 18.8515625, 18.6875
    vm = v ** (1.0 / m2)
    y = (np.maximum(vm - c1, 0.0) / (c2 - c3 * vm)) ** (1.0 / m1)
    q = np.rint(np.clip(y, 0, 1) * 65535).astype(">u2")
    return b"curv" + b"\0" * 4 + struct.pack(">I", n) + q.tobytes()


def _text_tag(s: str) -> bytes:
    enc = s.encode("utf-16-be")
    return (b"mluc" + b"\0" * 4 + struct.pack(">II", 1, 12)
            + b"enUS" + struct.pack(">II", len(enc), 28) + enc)


def _cicp_tag(prim=9, trc=16, matrix=0, full_range=1) -> bytes:
    return b"cicp" + b"\0" * 4 + bytes([prim, trc, matrix, full_range])


def build(desc: str = "Rec2020 Gamut with PQ Transfer") -> bytes:
    m = _rgb_to_xyz_d50()
    curve = _pq_curve()
    tags = [
        (b"desc", _text_tag(desc)),
        (b"cprt", _text_tag("Generated by png2hdr. No rights reserved.")),
        (b"wtpt", _xyz_tag(D50_XYZ)),
        (b"rXYZ", _xyz_tag(m[:, 0])),
        (b"gXYZ", _xyz_tag(m[:, 1])),
        (b"bXYZ", _xyz_tag(m[:, 2])),
        (b"rTRC", curve),
        (b"gTRC", curve),
        (b"bTRC", curve),
        (b"cicp", _cicp_tag()),
    ]

    table_size = 4 + 12 * len(tags)
    offset = 128 + table_size
    offset += (-offset) % 4
    entries, body, seen = [], bytearray(), {}
    for sig, data in tags:
        key = bytes(data)
        if key in seen:                    # share the identical TRC curves
            entries.append((sig, *seen[key])); continue
        pos = offset + len(body)
        entries.append((sig, pos, len(data)))
        seen[key] = (pos, len(data))
        body += data + b"\0" * ((-len(data)) % 4)

    size = offset + len(body)
    header = bytearray(128)
    struct.pack_into(">I4sI4s4s4s", header, 0, size, b"none", 0x04400000,
                     b"mntr", b"RGB ", b"XYZ ")
    header[36:40] = b"acsp"
    struct.pack_into(">III", header, 68, *(_s15f16(v) for v in D50_XYZ))

    out = bytearray(header)
    out += struct.pack(">I", len(entries))
    for sig, pos, ln in entries:
        out += struct.pack(">4sII", sig, pos, ln)
    out += b"\0" * ((-len(out)) % 4)
    out += body
    assert len(out) == size, (len(out), size)
    return bytes(out)


if __name__ == "__main__":
    p = build()
    print(len(p), "bytes")
    n = struct.unpack(">I", p[128:132])[0]
    for k in range(n):
        sig, o, s = struct.unpack(">4sII", p[132 + k * 12:144 + k * 12])
        extra = f"  -> {list(p[o+8:o+12])}" if sig == b"cicp" else ""
        print(" ", sig.decode(), s, extra)
